config-version: 1

# sqlite, mysql, or postgresql
type: sqlite
file: mbadges

host: localhost
port: 3306
name: mbadges
username: mbadges
password: ""

pool-size: 10
connection-timeout-millis: 10000
max-lifetime-millis: 1800000

# Optional full JDBC URL. Leave empty to use the settings above.
jdbc-url: ""
